export class Usuario {

   constructor(
   public Codigo: number,
   public CodigoIdentificacao: number,
   public Nome: string,
   public CodPessoa: number,
   public Senha: string,
   public DescontoMax: number,
   public Comissao: number,
   public CadUsuario: boolean,
   public BloqueiaCancelaProd: boolean,
   public CodigoFuncao: number,
   public CodigoEmpresa: number,
   public CodigoEmpregado: number,
   public MovimentaEstoqueES: boolean,
   public VerQuantiaCaixa: boolean,
   public devolverProduto: boolean,
   public PDV_EstornarRecbto: boolean,
   public PDV_CancelarPedido: boolean,
   public PDV_PermitirOutrasSaidas: boolean,
   public PDV_ModificarDescontoSistema: boolean,
   public PDV_PermitirTransfProduto: boolean,
   public PDV_CriarOrcamento: boolean,
   public Ret_VerCusto: boolean,
   public Ret_AlteraTabPreco: boolean,
   public AcessaFinanceiro: boolean,
   public AlteraProduto: boolean,
   public PDV_PermitirVendaClienteComTituloAtrasado: boolean,
   public PDV_PermitirVendaClienteSemLimiteCredito: boolean,
   public Meta: number,
   public OperadorCaixa: boolean,
   public AcessarRetaguarda: boolean,
   ) {}
}
